### ISSUE TITLE
I am facing a basic issue because of unclear README.md (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [mikakruschel/app-landing-page#2]
I downloaded this project on my local machine. and after click on index.html I am getting creepy code lines (Screenshot included) not an actual page.

I know I am making very basic mistake here as an android developer I didn't have knowledge about this so please help and make readme clear so that everyone can use this project without facing these basic problems.

![Screenshot](https://github.com/mikakruschel/app-landing-page/assets/49509445/5118d2a0-c848-4bb7-a530-f60f342af9d2)

**Comment by mikakruschel** [comment]
This repo uses Jekyll to build the webpage. Please check out https://jekyllrb.com/docs/usage/
